### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by Anoxia** [adhocore/php-cli#44]
I found this project by packagist, I need it, it's great!
thanks~

**Comment by adhocore** [comment]
thank you for kind words. can't wait to see what cool stuffs you will build using this package.
in the meantime may i ask you to have a look at [phint](https://github.com/adhocore/phint) 😊

**Comment by Anoxia** [comment]
It's developing! It's a high-performance asynchronous PHP microapplication based on [swoole](https://www.swoole.co.uk/), and I'll share it when it's done.

**Comment by adhocore** [comment]
is it done yet? 😇

**Comment by Anoxia** [comment]
> is it done yet? 😇

Yes, man, see [bee-framework](https://github.com/NufangTechnology/bee-skeleton)

**Comment by adhocore** [comment]
cool. `adhocore/php-cli` has now newer version release already :)

**Comment by Anoxia** [comment]
🙏, I will follow up the new version. In fact, the above framework is just for practice. I am developing a new microservice framework from scratch, focusing on command-line mode operation, and abandoning phpp CGI. At present, I am writing a command-line UI library, and I hope to realize more possibilities in command-line tools based on this library.

**Comment by Anoxia** [comment]
> 🙏, I will follow up the new version. In fact, the above framework is just for practice. I am developing a new microservice framework from scratch, focusing on command-line mode operation, and abandoning phpp CGI. At present, I am writing a command-line UI library, and I hope to realize more possibilities in command-line tools based on this library.

Although it is an excessive framework, its performance is very good, thanks to the Swoole coroutine advantage, the 2 core 4G machine echo service may reach 6w~7w QPS per second, MySQL writes 6k data per second, 9k data per second Inquire. Pressure measuring tool: wrk.
