### ISSUE TITLE
how to use interactor prompt hidden password 

### ISSUE THREAD

**Issue by shaukei** [adhocore/php-cli#47]
how to use interactor prompt hidden password

**Comment by adhocore** [comment]
currently no. but i think i will add it this weekend if you can wait.

and thanks for trying it out and opening issue. :)

**Comment by shaukei** [comment]
Great. I want to finish the weekend right away. So I can experience this function.Thank you

**Comment by adhocore** [comment]
implemented in [v0.4.0](https://github.com/adhocore/php-cli/releases/tag/0.4.0)

docs: https://github.com/adhocore/php-cli#prompt-hidden

but not for [windows](https://stackoverflow.com/a/27395651) yet

**Comment by shaukei** [comment]
thx!

**Comment by adhocore** [comment]
windows support in [0.5.0](https://github.com/adhocore/php-cli/releases/tag/0.5.0)
