### ISSUE TITLE
Add development tools

### ISSUE THREAD

**Issue by pattisahusiwa** [adhocore/php-cli#58]
It would be nice if you can add coding style and static analyzer? I've checked this repo with PHPStan and found at least 68 errors.

**Comment by adhocore** [comment]
sure thing, please contrib. thanks

**Comment by pattisahusiwa** [comment]
Unit tests failed after adding `declare(strict_types=1)`  to all PHP files. Can you add the directive and fix the code?

Also please check this issue https://github.com/phpstan/phpstan/issues/3916#issue-714277268

**Comment by adhocore** [comment]
https://github.com/phpstan/phpstan/issues/3916#issuecomment-703231243

ohh, however in practice this is not infinite loop - maybe the php docs is misleading.
the tests are working great and as expected with the code we have.
i think this specific file can be blacklisted/ignored?

**Comment by adhocore** [comment]
```php
while (($bucket = stream_bucket_make_writeable($in)) && $bucket->data !== '') {
    static::$buffer .= $bucket->data;
}
```

**Comment by pattisahusiwa** [comment]
It's ok, we can ignore the error.

I'll working on phpstan integration, but we need to collaborate on the PR.  What do you think?

**Comment by adhocore** [comment]
@pattisahusiwa not sure if we need to close this ticket due to lack of activity :D
