### ISSUE TITLE
In the Composer script, the tools used are external, and I want to make it easier for them to reside in dependencies

### ISSUE THREAD

**Issue by dongasai** [adhocore/php-cli#62]
I think I could start a PR

**Comment by adhocore** [comment]
> the tools used are external, and I want to make it easier for them to reside in dependencies

sorry what is external here?

**Comment by dongasai** [comment]
Examples are 'test:cov' needed 'pcov', and 'cs:sniff' needed 'phpcs'

**Comment by adhocore** [comment]
pcov is pecl installable extension for code coverage, while phpcs might be composer dep
(i think first need to check #57 and #59)

**Comment by dongasai** [comment]
#59 The "tools/ PHPCS "executable and the "phpunit" executable do not exist

**Comment by pattisahusiwa** [comment]
`phpcs` and `phpcbf` are installed using https://github.com/phar-io/phive, please check the github page. `phpunit` should be installed by `composer`.

**Comment by dongasai** [comment]
因此，我的意思是，这可以用于composer中的依赖项管理。
而不是单独安装

**Comment by pattisahusiwa** [comment]
Composer should be used to manage project dependencies only, not the external tools. That's why Bergmann doesn't recommend installing phpunit using composer.
