### ISSUE TITLE
Unable to execute certain commands using `Ahc\Cli\Helper\Shell`

### ISSUE THREAD

**Issue by mrmusselman1** [adhocore/php-cli#74]
I'm unable to execute the following simplified version of something I'm doing in a project that uses `adhocore/php-cli` after upgrading from version `0.9.1` to verison `v1.2.0`. I'm running on CentOS. 

```php
$shell = new \Ahc\Cli\Helper\Shell('semanage');
$shell->execute(false);
error_log($shell->getOutput());
error_log($shell->getErrorOutput());
error_log($shell->getExitCode());
```

In version `0.9.1` the output includes the help text for `semanage` and the exit code of `0`. When I run this in version `1.2.0`, I get the exit code of `127`.

**Comment by mrmusselman1** [comment]
This is my first time contributing to a GitHub repo that is not my own, so I apologize in advance if I did not follow the correct process. I forked the repo and created a pull request against a branch in my fork.

**Comment by adhocore** [comment]
oh thanks and congrats for first contribution. and i think process is fine.
