### ISSUE TITLE
Exception Propagation

### ISSUE THREAD

**Issue by jfrisella** [adhocore/php-cli#79]
Is there a method for exception propagation?  The `handle` method currently catches and outputs the stacktrace.  I'm looking to capture the exception and send to a centralized issue tracking site.  I can capture the $exitCode but the original exception stacktrace and message is what i'm after.

thanks for any help.

**Comment by jfrisella** [comment]
Just to clarify, I'm using the PHP 7 version of the library.

**Comment by adhocore** [comment]
thank you, checking it soon :)

**Comment by adhocore** [comment]
the handle method is meant to be used as end product/tool so maybe not sensible to propagate that unless you wrap this within another product/tool.
however i understood your usecase, and it does require some compatibility breaks. so the best we can do is we can **assign the thrown exception of `handle()` to a variable to retrieve later** (needs to change the code but no BC breaks) and _reset onExit to not `exit`_ (this is already possible).
do you have any interest on contributing to that part in bold above? thanks :rocket:

**Comment by adhocore** [comment]
fixed in #80 , released as v1.4.0
