### ISSUE TITLE
Wrong order of arguments when using application

### ISSUE THREAD

**Issue by tbreuss** [adhocore/php-cli#95]
I noticed that when using the cli application and adding two or more arguments for a command, the ordering of the arguments in the help may differ from the setup.

This is what I configured for a certain command:

<img width="774" alt="Bildschirmfoto 2024-01-22 um 14 44 13" src="https://github.com/adhocore/php-cli/assets/1334161/7b9ad657-974c-41b5-a9c4-b7c2d1569962">

And this is what the help for the given command outputs:

<img width="682" alt="Bildschirmfoto 2024-01-22 um 14 44 52" src="https://github.com/adhocore/php-cli/assets/1334161/ea1d9a91-f918-4979-8f41-3c31a6ffdaaf">

It seems like the output of the help command orders the arguments by name ascending.

**Comment by adhocore** [comment]
oh that if true, seems like visual issue only. could you pls check if the functioning is as expected even though help output is different. thank you

**Comment by adhocore** [comment]
thanks for feedback, fixed in #97

**Comment by tbreuss** [comment]
> thanks for feedback, fixed in #97

Thanks for your work!
